# Change these first
owner: weelone # Your GitHub organization or username, where this repository lives
repo: echobell-upptime # The name of this repository

sites:
  - name: Echobell API
    url: https://api.echobell.one/v1/announcements
  - name: Echobell Website
    url: https://echobell.one

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.echobell.one
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.echobell.one/images/branded-logo.svg
  name: Echobell Status
  introTitle: "[**Echobell**](https://echobell.one) Status Page"
  introMessage: "Monitoring the status of [**Echobell**](https://echobell.one) services."
  navbar:
    - title: Status
      href: /
    - title: Echobell
      href: https://echobell.one

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
